name: App Release

on:
  push:
    branches: [master]
    paths:
      - 'apps/web/package.json'
      - 'apps/web/CHANGELOG.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version
        id: readver
        shell: bash
        run: |
          set -euo pipefail
          VERSION=$(node -p "require('./apps/web/package.json').version")
          echo "VERSION=$VERSION" | tee -a "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create tag if missing
        shell: bash
        run: |
          set -euo pipefail
          TAG="web-v${{ steps.readver.outputs.version }}"
          git fetch --tags
          if git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "$TAG" -m "web v${{ steps.readver.outputs.version }}"
            git push origin "$TAG"
          fi

      - name: Extract top release notes
        id: notes
        shell: bash
        env:
          VERSION: ${{ steps.readver.outputs.version }}
        run: |
          set -euo pipefail
          if [ ! -f apps/web/CHANGELOG.md ]; then
            printf "# %s\n" "$VERSION" > RELEASE_NOTES.md
            exit 0
          fi
          # ——— запуск JS-кода через heredoc без интерполяции шеллом ———
          node - <<'NODE'
          const fs = require('fs');
          const version = process.env.VERSION;
          const md = fs.readFileSync('apps/web/CHANGELOG.md','utf8');
          const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
          const re = new RegExp('##\\s*' + esc(version) + '[\\s\\S]*?(?=\\n##\\s|$)');
          const m = md.match(re);
          fs.writeFileSync('RELEASE_NOTES.md', m ? m[0] : ('# ' + version + '\\n'));
          NODE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: web-v${{ steps.readver.outputs.version }}
          name: web v${{ steps.readver.outputs.version }}
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
