name: Changesets
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'          # кэш для pnpm

      # ✅ Вместо pnpm/action-setup — Corepack, он возьмёт версию из package.json -> packageManager
      - run: corepack enable

      - run: pnpm --version      # для диагностики увидишь 10.18.0 (или что указано у тебя)

      - run: pnpm i --frozen-lockfile

      # Создаёт/обновляет PR "Version Packages" (без публикации в npm)
      - uses: changesets/action@v1
        with:
          version: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
